### ISSUE TITLE
Error while loading Application Wizards

### ISSUE THREAD

**Issue by yohannrongere** [SAP/yeoman-ui#603]
Hello,
Sorry I am a beginner in SAP Fiori applications. I am using Application Wizard to create my SAP Fiori Application using Fiori Elements. It was working fine those lasts days (I've created a new app 2 days ago) but now, when I want to create a new application with Application Wizard, I have this error : 
![image](https://user-images.githubusercontent.com/84918786/119840267-20be0d80-bf05-11eb-9ed1-e0e8d9624e53.png)
I don't know what does it means, but the Application Wizard can't be launched. I was using the version 1.2.6 and it was not working. I've installed the new version 1.3.3 but it still doesn't work. I tried to uninstall, reinstall the Apps and, of course, restart Visual Studio.
Certainly I did something wrong but I don't know what (maybe it something with this professional laptop). Could you help me ?

Thanks a lot !

**Comment by slavik-lvovsky** [comment]
Please explain how to reproduce the issue.

**Comment by yohannrongere** [comment]
In Visual Studio code (version 1.56.2), I launch the Commande Palette (Ctrl+Shift+P) and I choose Fiori : Open Application Generator
![image](https://user-images.githubusercontent.com/84918786/119846943-df306100-bf0a-11eb-8750-96e4c3f3d156.png)
Then I can see the Tab Template Wizard appearing and immediately disappearing... Finally the message that i have the message i put in my issue.

Thank you for your message.

**Comment by slavik-lvovsky** [comment]
What should I install to get "Fiori: Open Application generator" command ?

**Comment by yohannrongere** [comment]
I have installed the extension SAP Fiori Tools - Extension Pack in Visual Studio Code and I have installed the new version of Application Wizard (1.3.3) using VSIX file

**Comment by slavik-lvovsky** [comment]
I have installed SAP Fiori Tools and the command worked with Application Wizard version 1.2.6
I will check now with version 1.3.3

**Comment by slavik-lvovsky** [comment]
Version 1.3.3 works too. I do not see any problem.
What is your environment? Mine is Windows 10

**Comment by yohannrongere** [comment]
I use Windows 10 too. What I don't understand that it was working fine 2 days ago, I am sure it something with my laptop but I don't know what. Maybe I should uninstall Visual Studio code and reinstall it with all the extensions.
Thanks again

**Comment by slavik-lvovsky** [comment]
The error says that it cannot find module called "find-up".

**Comment by yohannrongere** [comment]
Yes I see that but i have no idea how to fix it

**Comment by slavik-lvovsky** [comment]
Try to uninstall and install again  SAP Fiori Tools. In Application Wizard we do not use this module, at least directly.
Try to install @sap/generator-fiori generator from npmjs and run it by using Open Template Wizard command. 
Does it work?

**Comment by slavik-lvovsky** [comment]
I did all the steps above and everything works as expected.
Both Fiori tool and Application Wizard work fine.
It is probably something on your computer.
What node version do you have ?

**Comment by yohannrongere** [comment]
Thanks a lot, it worked ! Sorry to answer only now I've been busy.
Now I can create my fiori apps 👍
